# GolangCI-Lint configuration
# See https://github.com/golangci/golangci-lint#configuration

run:
  tests: false
  timeout: 2m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

    enable:
      - atomicalign
    enable-all: false
    disable:
      - shadow
    disable-all: false
  # golint:
  #   min-confidence: 0.8
  # gocyclo:
  #   min-complexity: 30
  # gocognit:
  #   min-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 100

linters:
  enable-all: true
  disable:
    - vetshadow
    - gocyclo
    - unparam
    - nakedret
    - dupl
    - gosec
    - gochecknoinits
    - gochecknoglobals
    - errcheck
    - staticcheck
    - stylecheck
    - wsl
    - interfacer
    - gomnd

    # TODO(charliekenney23): enable these rules once compliant
    - prealloc
    - funlen
    - whitespace
    - godox
    - unconvert
    - gocognit
    - unused
    - gosimple
    - gocritic
    - scopelint

    # These ignores have been added to maintain compatibility with the existing codebase.
    # These issues should be resolved at a later date.
    - wrapcheck
    - varnamelen
    - nonamedreturns
    - nlreturn
    - thelper
    - predeclared
    - nilnil
    - ifshort
    - goerr113
    - errchkjson
    - cyclop
    - nestif
    - maintidx
    - forcetypeassert
    - exhaustruct
    - exhaustivestruct
    - exhaustive
    - errorlint
    - forbidigo
    - godot
    - typecheck

  fast: false
