version: "2"
run:
  tests: true

linters:
  default: standard
  settings:
    dupl:
      threshold: 100
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
    gomoddirectives:
      replace-allow-list:
        - github.com/linode/linodego
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # disable deprecation checks
      - linters:
          - staticcheck
        text: "SA1019:"

      # disable error message checks
      - linters:
          - staticcheck
        text: "ST1005:"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: strict
