name: Continuous Integration
on: 
  - pull_request
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      
      - name: Check docs
        run: make docs-check
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8
      - name: Tidy
        run: go mod tidy
      - run: make deps
      - name: tflint
        run: make tflint
      - name: Fail if changes
        run: git diff-index --exit-code HEAD
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go version
      - run: make deps
      - name: Unit tests
        run: make test-unit

  dependency-review:
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: on-failure

  gosec_scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G104 ./...
